config/routes.rb
Rails.application.routes.draw do
  resources :machines

  resources :internal_values

  resources :schedules

  resources :backlogs

  resources :inventories

  resources :products

  resources :suppliers
  
  match 'refreshAll', to: 'application#refreshAll', via: :get
  
  root :to => 'backlogs#index'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :backlog
  
  #validates_uniqueness_of :id, scope: [:backlog_id, :seq]
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
      @backlogId = params[:backlogId]
      
      if params[:idList] then
        #Convert back escape character of ","
        params[:idList]["%2C"] = "," if params[:idList]["%2C"]
        param_a = params[:idList].split(",").map { |s| s.to_i }
        
        @schedules = Schedule.find(param_a)
      else
        @schedules = Schedule.all
      end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
    @backlogId = ""
    @sono = ""
    @productCode = ""
    if params[:backlogId] then
      backlog = Backlog.find(params[:backlogId])
      @backlogId = backlog.id
      @sono = backlog.sono
      @productCode = backlog.product.code
    end
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:backlog_id, :sono, :productCode, :deliveryDate, :priority, :amt, :seq, :scheduler)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<script>
      $(function() {
          $( "#datetimepicker1" ).datepicker();
      });
  </script>
<%= form_for @schedule, :html => { :class => "form-horizontal schedule" } do |f| %>

    <% if @schedule.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @schedule.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :backlog_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :backlog_id, :class => 'form-control', :value => @backlogId %>
    </div>
    <%= error_span(@schedule[:backlog_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :sono, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sono, :class => 'form-control', :value => @sono %>
    </div>
    <%= error_span(@schedule[:sono]) %>
  </div>
  <div class="control-group">
    <%= f.label :productCode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :productCode, :class => 'form-control', :value => @productCode %>
    </div>
    <%= error_span(@schedule[:productCode]) %>
  </div>
  <div class="control-group">
    <%= f.label :deliveryDate, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :deliveryDate, :class => 'form-control' %>
    </div>
    <%= error_span(@schedule[:deliveryDate]) %>
  </div>
  <div class="control-group">
    <%= f.label :priority, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :priority, :class => 'form-control' %>
    </div>
    <%= error_span(@schedule[:priority]) %>
  </div>
  <div class="control-group">
    <%= f.label :amt, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amt, :class => 'form-control' %>
    </div>
    <%= error_span(@schedule[:amt]) %>
  </div>
  <div class="control-group">
    <%= f.label :seq, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :seq, :class => 'form-control' %>
    </div>
    <%= error_span(@schedule[:seq]) %>
  </div>
  <div class="control-group">
    <%= f.label :scheduler, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :scheduler, :class => 'form-control' %>
    </div>
    <%= error_span(@schedule[:scheduler]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            schedules_path, :class => 'btn btn-default' %>

<% end %>

app/views/schedules/edit.html.erb
<%- model_class = Schedule -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/schedules/index.html.erb
<%- model_class = Schedule -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped" id="schedules">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:backlog_id) %></th>
      <th><%= model_class.human_attribute_name(:sono) %></th>
      <th><%= model_class.human_attribute_name(:productCode) %></th>
      <th><%= model_class.human_attribute_name(:deliveryDate) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th><%= model_class.human_attribute_name(:amt) %></th>
      <th><%= model_class.human_attribute_name(:seq) %></th>
      <th><%= model_class.human_attribute_name(:scheduler) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= link_to schedule.id, schedule_path(schedule) %></td>
        <td><%= schedule.backlog_id %></td>
        <td><%= schedule.sono %></td>
        <td><%= schedule.productCode %></td>
        <td><%= schedule.deliveryDate %></td>
        <td><%= schedule.priority %></td>
        <td><%= schedule.amt %></td>
        <td><%= schedule.seq %></td>
        <td><%= schedule.scheduler %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_schedule_path(schedule), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      schedule_path(schedule),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_schedule_path(:backlogId => @backlogId ),
            :class => 'btn btn-primary'%>

app/views/schedules/new.html.erb
<%- model_class = Schedule -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/schedules/show.html.erb
<%- model_class = Schedule -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:backlog_id) %>:</strong></dt>
  <dd><%= @schedule.backlog_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sono) %>:</strong></dt>
  <dd><%= @schedule.sono %></dd>
  <dt><strong><%= model_class.human_attribute_name(:productCode) %>:</strong></dt>
  <dd><%= @schedule.productCode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deliveryDate) %>:</strong></dt>
  <dd><%= @schedule.deliveryDate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:priority) %>:</strong></dt>
  <dd><%= @schedule.priority %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amt) %>:</strong></dt>
  <dd><%= @schedule.amt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:seq) %>:</strong></dt>
  <dd><%= @schedule.seq %></dd>
  <dt><strong><%= model_class.human_attribute_name(:scheduler) %>:</strong></dt>
  <dd><%= @schedule.scheduler %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              schedules_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_schedule_path(@schedule), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              schedule_path(@schedule),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>