config/routes.rb
Rails.application.routes.draw do
  resources :machines

  resources :internal_values

  resources :schedules

  resources :backlogs

  resources :inventories

  resources :products

  resources :suppliers
  
  match 'refreshAll', to: 'application#refreshAll', via: :get
  
  root :to => 'backlogs#index'

end

app/models/backlog.rb
class Backlog < ActiveRecord::Base
  belongs_to :product
  has_many :schedules
  
  def min
    self.backlog/self.product.speed
  end
  
  def scheduledAmt
    if self.schedules then
      self.schedules.sum(:amt)
    else
      0
    end
  end
  
  def schedulesKey
    schedulesKeyList = ""
    self.schedules.each_with_index do |sch, index|
      schedulesKeyList = schedulesKeyList + sch.id.to_s + ","
    end
    
    schedulesKeyList.chomp(',')
  end
  
  def weightBacklog
    self.backlog * self.product.estWeight
  end
  
  def deliveryDate
    if self.schedules.first then
      self.schedules.first.deliveryDate
    else
      ""
    end
  end
end

app/controllers/backlogs_controller.rb
class BacklogsController < ApplicationController
  before_action :set_backlog, only: [:show, :edit, :update, :destroy]

  # GET /backlogs
  # GET /backlogs.json
  def index
    @backlogs = Backlog.all
    @machineLists = Machine.all
  end

  # GET /backlogs/1
  # GET /backlogs/1.json
  def show
  end

  # GET /backlogs/new
  def new
    @backlog = Backlog.new
  end

  # GET /backlogs/1/edit
  def edit
  end

  # POST /backlogs
  # POST /backlogs.json
  def create
    @backlog = Backlog.new(backlog_params)

    respond_to do |format|
      if @backlog.save
        format.html { redirect_to @backlog, notice: 'Backlog was successfully created.' }
        format.json { render :show, status: :created, location: @backlog }
      else
        format.html { render :new }
        format.json { render json: @backlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backlogs/1
  # PATCH/PUT /backlogs/1.json
  def update
    respond_to do |format|
      if @backlog.update(backlog_params)
        format.html { redirect_to @backlog, notice: 'Backlog was successfully updated.' }
        format.json { render :show, status: :ok, location: @backlog }
      else
        format.html { render :edit }
        format.json { render json: @backlog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backlogs/1
  # DELETE /backlogs/1.json
  def destroy
    @backlog.destroy
    respond_to do |format|
      format.html { redirect_to backlogs_url, notice: 'Backlog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backlog
      @backlog = Backlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def backlog_params
      params.require(:backlog).permit(:custname, :product_id, :productCode, :sono, :orderDate, :orderAmt, :backlog)
    end
    

end

app/helpers/backlogs_helper.rb
module BacklogsHelper
end

app/views/backlogs/_form.html.erb
<%= form_for @backlog, :html => { :class => "form-horizontal backlog" } do |f| %>

    <% if @backlog.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@backlog.errors.count, "error") %> prohibited this backlog from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @backlog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :custname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :custname, :class => 'form-control' %>
    </div>
    <%= error_span(@backlog[:custname]) %>
  </div>
  <div class="control-group">
    <%= f.label :product_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :product_id, :class => 'form-control' %>
    </div>
    <%= error_span(@backlog[:product_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :productCode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :productCode, :class => 'form-control' %>
    </div>
    <%= error_span(@backlog[:productCode]) %>
  </div>
  <div class="control-group">
    <%= f.label :sono, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sono, :class => 'form-control' %>
    </div>
    <%= error_span(@backlog[:sono]) %>
  </div>
  <div class="control-group">
    <%= f.label :orderDate, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :orderDate, :class => 'form-control' %>
    </div>
    <%= error_span(@backlog[:orderDate]) %>
  </div>
  <div class="control-group">
    <%= f.label :orderAmt, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :orderAmt, :class => 'form-control' %>
    </div>
    <%= error_span(@backlog[:orderAmt]) %>
  </div>
  <div class="control-group">
    <%= f.label :backlog, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :backlog, :class => 'form-control' %>
    </div>
    <%= error_span(@backlog[:backlog]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            backlogs_path, :class => 'btn btn-default' %>

<% end %>

app/views/backlogs/edit.html.erb
<%- model_class = Backlog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/backlogs/index.html.erb
<%- model_class = Backlog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped" id="dashboards">
  <thead>
    <tr>
      <th><%= "Machine" %></th>
      <th class="text-right"><%=  "Weekly Mins" %></th>
      <th class="text-right"><%=  "Balance Mins" %></th>
      <th class="text-right"><%=  "Backlog Units" %></th>
      <th class="text-right"><%=  "Balance Units" %></th>
      <th class="text-right"><%=  "Scheduled Units" %></th>
    </tr>
  </thead>
  <tbody>
    <% @machineLists.each do |ml| %>
      <tr>
        <td><%= ml.name %></td>
        <td class="text-right"><%= number_to_currency(ml.mins, precision:0, unit: "") %></td>
        <td class="text-right"><%= number_to_currency(ml.totalMinsBal, precision:0, unit: "") %>
            (<%= number_to_percentage(ml.pctUsed, precision: 1) %>)</td>
        <td class="text-right"><%= number_to_currency(ml.totalBacklogsUnit, precision:0, unit: "") %></td>
        <td class="text-right"><%= number_to_currency(ml.totalBalUnit, precision:0, unit: "") %></td>
        <td class="text-right"><%= number_to_currency(ml.totalScheduledUnit, precision:0, unit: "") %>
            (<%= number_to_percentage(ml.pctScheduled, precision: 1) %>)</td>
      </tr>
    <% end %>
  </tbody>
</table>
<table class="table table-striped" id="backlogs">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:orderDate) %></th>
      <th><%= model_class.human_attribute_name(:custname) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:stockLeft) %></th>
      <th><%= model_class.human_attribute_name(:backlog) %></th>
      <th><%= model_class.human_attribute_name(:scheduled) %></th>
      <th><%= model_class.human_attribute_name(:weight) %></th>
      <th><%= model_class.human_attribute_name(:scheduledDate) %></th>
      <th><%= model_class.human_attribute_name(:machine) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @backlogs.each do |backlog| %>
      <tr>
        <td><%= backlog.orderDate %></td>
        <td><%= backlog.custname %></td>
        <td><%= backlog.product.name %></td>
        <td><%= backlog.product.stockUnscheduled %></td>
        <td><%= backlog.scheduledAmt > backlog.backlog ? content_tag(:strong, backlog.backlog) : backlog.backlog %></td>
        <td><%= link_to backlog.scheduledAmt, schedules_path(idList: backlog.schedulesKey, backlogId: backlog.id) %></td>
        <td><%= number_to_currency(backlog.weightBacklog, precision: 0, unit: "") %></td>
        <td><%= backlog.deliveryDate %></td>
        <td><%= backlog.product.machine.name %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_backlog_path(backlog), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      backlog_path(backlog),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_backlog_path,
            :class => 'btn btn-primary' %>

app/views/backlogs/new.html.erb
<%- model_class = Backlog -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/backlogs/show.html.erb
<%- model_class = Backlog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:custname) %>:</strong></dt>
  <dd><%= @backlog.custname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @backlog.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:productCode) %>:</strong></dt>
  <dd><%= @backlog.productCode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sono) %>:</strong></dt>
  <dd><%= @backlog.sono %></dd>
  <dt><strong><%= model_class.human_attribute_name(:orderDate) %>:</strong></dt>
  <dd><%= @backlog.orderDate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:orderAmt) %>:</strong></dt>
  <dd><%= @backlog.orderAmt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:backlog) %>:</strong></dt>
  <dd><%= @backlog.backlog %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              backlogs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_backlog_path(@backlog), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              backlog_path(@backlog),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>