config/routes.rb
Rails.application.routes.draw do
  resources :machines

  resources :internal_values

  resources :schedules

  resources :backlogs

  resources :inventories

  resources :products

  resources :suppliers
  
  match 'refreshAll', to: 'application#refreshAll', via: :get
  
  root :to => 'backlogs#index'

end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_many :products
  
  def totalMinsBal
    totalMinsBacklogs = 0
    
    self.products.each do |p|
      totalMinsBacklogs = totalMinsBacklogs + p.sumMinsBal
    end
    
    totalMinsBacklogs
  end
  
  def totalBalUnit
    totalBal = 0
    
    self.products.each do |p|
      totalBal = totalBal + p.sumBalance
    end
    
    totalBal
  end
  
  def totalBacklogsUnit
    totalBacklogs = 0
    
    self.products.each do |p|
      totalBacklogs = totalBacklogs + p.sumBacklog
    end
    
    totalBacklogs
  end
  
  def totalScheduledUnit
    totalScheduled = 0
    
    self.products.each do |p|
      totalScheduled = totalScheduled + p.sumScheduled
    end
    
    totalScheduled
  end
  
  def mins
    self.workdays*self.workhours*60
  end
  
  def pctUsed
    self.totalMinsBal/self.mins*100
  end
  
  def pctScheduled
    self.totalScheduledUnit.to_f/self.totalBacklogsUnit.to_f*100
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]

  # GET /machines
  # GET /machines.json
  def index
    @machines = Machine.all
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines
  # POST /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1
  # PATCH/PUT /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url, notice: 'Machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_params
      params.require(:machine).permit(:name, :workdays, :workhours)
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_for @machine, :html => { :class => "form-horizontal machine" } do |f| %>

    <% if @machine.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@machine.errors.count, "error") %> prohibited this machine from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @machine.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@machine[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :workdays, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :workdays, :class => 'form-control' %>
    </div>
    <%= error_span(@machine[:workdays]) %>
  </div>
  <div class="control-group">
    <%= f.label :workhours, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :workhours, :class => 'form-control' %>
    </div>
    <%= error_span(@machine[:workhours]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            machines_path, :class => 'btn btn-default' %>

<% end %>

app/views/machines/edit.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/machines/index.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:workdays) %></th>
      <th><%= model_class.human_attribute_name(:workhours) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= link_to machine.id, machine_path(machine) %></td>
        <td><%= machine.name %></td>
        <td><%= machine.workdays %></td>
        <td><%= machine.workhours %></td>
        <td><%=l machine.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_machine_path(machine), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      machine_path(machine),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_machine_path,
            :class => 'btn btn-primary' %>

app/views/machines/new.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/machines/show.html.erb
<%- model_class = Machine -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @machine.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:workdays) %>:</strong></dt>
  <dd><%= @machine.workdays %></dd>
  <dt><strong><%= model_class.human_attribute_name(:workhours) %>:</strong></dt>
  <dd><%= @machine.workhours %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              machines_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_machine_path(@machine), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              machine_path(@machine),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>